// Code generated by "enumer -type dedupCmdKind"; DO NOT EDIT.

package loggers

import (
	"fmt"
	"strings"
)

const _dedupCmdKindName = "dedupCmdLogdedupCmdClose"

var _dedupCmdKindIndex = [...]uint8{0, 11, 24}

const _dedupCmdKindLowerName = "dedupcmdlogdedupcmdclose"

func (i dedupCmdKind) String() string {
	if i >= dedupCmdKind(len(_dedupCmdKindIndex)-1) {
		return fmt.Sprintf("dedupCmdKind(%d)", i)
	}
	return _dedupCmdKindName[_dedupCmdKindIndex[i]:_dedupCmdKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _dedupCmdKindNoOp() {
	var x [1]struct{}
	_ = x[dedupCmdLog-(0)]
	_ = x[dedupCmdClose-(1)]
}

var _dedupCmdKindValues = []dedupCmdKind{dedupCmdLog, dedupCmdClose}

var _dedupCmdKindNameToValueMap = map[string]dedupCmdKind{
	_dedupCmdKindName[0:11]:       dedupCmdLog,
	_dedupCmdKindLowerName[0:11]:  dedupCmdLog,
	_dedupCmdKindName[11:24]:      dedupCmdClose,
	_dedupCmdKindLowerName[11:24]: dedupCmdClose,
}

var _dedupCmdKindNames = []string{
	_dedupCmdKindName[0:11],
	_dedupCmdKindName[11:24],
}

// dedupCmdKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func dedupCmdKindString(s string) (dedupCmdKind, error) {
	if val, ok := _dedupCmdKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _dedupCmdKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to dedupCmdKind values", s)
}

// dedupCmdKindValues returns all values of the enum
func dedupCmdKindValues() []dedupCmdKind {
	return _dedupCmdKindValues
}

// dedupCmdKindStrings returns a slice of all String values of the enum
func dedupCmdKindStrings() []string {
	strs := make([]string, len(_dedupCmdKindNames))
	copy(strs, _dedupCmdKindNames)
	return strs
}

// IsAdedupCmdKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i dedupCmdKind) IsAdedupCmdKind() bool {
	for _, v := range _dedupCmdKindValues {
		if i == v {
			return true
		}
	}
	return false
}
