// Code generated by "enumer -type CalcMode -linecomment -text"; DO NOT EDIT.

package servers

import (
	"fmt"
	"strings"
)

const _CalcModeName = "syncasyncparallel"

var _CalcModeIndex = [...]uint8{0, 4, 9, 17}

const _CalcModeLowerName = "syncasyncparallel"

func (i CalcMode) String() string {
	i -= 1
	if i >= CalcMode(len(_CalcModeIndex)-1) {
		return fmt.Sprintf("CalcMode(%d)", i+1)
	}
	return _CalcModeName[_CalcModeIndex[i]:_CalcModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CalcModeNoOp() {
	var x [1]struct{}
	_ = x[Sync-(1)]
	_ = x[Async-(2)]
	_ = x[Parallel-(3)]
}

var _CalcModeValues = []CalcMode{Sync, Async, Parallel}

var _CalcModeNameToValueMap = map[string]CalcMode{
	_CalcModeName[0:4]:       Sync,
	_CalcModeLowerName[0:4]:  Sync,
	_CalcModeName[4:9]:       Async,
	_CalcModeLowerName[4:9]:  Async,
	_CalcModeName[9:17]:      Parallel,
	_CalcModeLowerName[9:17]: Parallel,
}

var _CalcModeNames = []string{
	_CalcModeName[0:4],
	_CalcModeName[4:9],
	_CalcModeName[9:17],
}

// CalcModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CalcModeString(s string) (CalcMode, error) {
	if val, ok := _CalcModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CalcModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CalcMode values", s)
}

// CalcModeValues returns all values of the enum
func CalcModeValues() []CalcMode {
	return _CalcModeValues
}

// CalcModeStrings returns a slice of all String values of the enum
func CalcModeStrings() []string {
	strs := make([]string, len(_CalcModeNames))
	copy(strs, _CalcModeNames)
	return strs
}

// IsACalcMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CalcMode) IsACalcMode() bool {
	for _, v := range _CalcModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for CalcMode
func (i CalcMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CalcMode
func (i *CalcMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = CalcModeString(string(text))
	return err
}
