// Code generated by "enumer -type ServerType -linecomment -text"; DO NOT EDIT.

package servers

import (
	"fmt"
	"strings"
)

const _ServerTypeName = "stdhttpfasthttp"

var _ServerTypeIndex = [...]uint8{0, 7, 15}

const _ServerTypeLowerName = "stdhttpfasthttp"

func (i ServerType) String() string {
	i -= 1
	if i >= ServerType(len(_ServerTypeIndex)-1) {
		return fmt.Sprintf("ServerType(%d)", i+1)
	}
	return _ServerTypeName[_ServerTypeIndex[i]:_ServerTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ServerTypeNoOp() {
	var x [1]struct{}
	_ = x[ServerStd-(1)]
	_ = x[ServerFast-(2)]
}

var _ServerTypeValues = []ServerType{ServerStd, ServerFast}

var _ServerTypeNameToValueMap = map[string]ServerType{
	_ServerTypeName[0:7]:       ServerStd,
	_ServerTypeLowerName[0:7]:  ServerStd,
	_ServerTypeName[7:15]:      ServerFast,
	_ServerTypeLowerName[7:15]: ServerFast,
}

var _ServerTypeNames = []string{
	_ServerTypeName[0:7],
	_ServerTypeName[7:15],
}

// ServerTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ServerTypeString(s string) (ServerType, error) {
	if val, ok := _ServerTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ServerTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ServerType values", s)
}

// ServerTypeValues returns all values of the enum
func ServerTypeValues() []ServerType {
	return _ServerTypeValues
}

// ServerTypeStrings returns a slice of all String values of the enum
func ServerTypeStrings() []string {
	strs := make([]string, len(_ServerTypeNames))
	copy(strs, _ServerTypeNames)
	return strs
}

// IsAServerType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ServerType) IsAServerType() bool {
	for _, v := range _ServerTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for ServerType
func (i ServerType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ServerType
func (i *ServerType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ServerTypeString(string(text))
	return err
}
