// Code generated by "enumer -type asyncCmdKind"; DO NOT EDIT.

package calculators

import (
	"fmt"
	"strings"
)

const _asyncCmdKindName = "asyncCmdCalcasyncCmdStop"

var _asyncCmdKindIndex = [...]uint8{0, 12, 24}

const _asyncCmdKindLowerName = "asynccmdcalcasynccmdstop"

func (i asyncCmdKind) String() string {
	if i >= asyncCmdKind(len(_asyncCmdKindIndex)-1) {
		return fmt.Sprintf("asyncCmdKind(%d)", i)
	}
	return _asyncCmdKindName[_asyncCmdKindIndex[i]:_asyncCmdKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _asyncCmdKindNoOp() {
	var x [1]struct{}
	_ = x[asyncCmdCalc-(0)]
	_ = x[asyncCmdStop-(1)]
}

var _asyncCmdKindValues = []asyncCmdKind{asyncCmdCalc, asyncCmdStop}

var _asyncCmdKindNameToValueMap = map[string]asyncCmdKind{
	_asyncCmdKindName[0:12]:       asyncCmdCalc,
	_asyncCmdKindLowerName[0:12]:  asyncCmdCalc,
	_asyncCmdKindName[12:24]:      asyncCmdStop,
	_asyncCmdKindLowerName[12:24]: asyncCmdStop,
}

var _asyncCmdKindNames = []string{
	_asyncCmdKindName[0:12],
	_asyncCmdKindName[12:24],
}

// asyncCmdKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func asyncCmdKindString(s string) (asyncCmdKind, error) {
	if val, ok := _asyncCmdKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _asyncCmdKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to asyncCmdKind values", s)
}

// asyncCmdKindValues returns all values of the enum
func asyncCmdKindValues() []asyncCmdKind {
	return _asyncCmdKindValues
}

// asyncCmdKindStrings returns a slice of all String values of the enum
func asyncCmdKindStrings() []string {
	strs := make([]string, len(_asyncCmdKindNames))
	copy(strs, _asyncCmdKindNames)
	return strs
}

// IsAasyncCmdKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i asyncCmdKind) IsAasyncCmdKind() bool {
	for _, v := range _asyncCmdKindValues {
		if i == v {
			return true
		}
	}
	return false
}
