// Code generated by "enumer -type aggrCmdKind"; DO NOT EDIT.

package metrics

import (
	"fmt"
	"strings"
)

const _aggrCmdKindName = "aggrCmdDataaggrCmdStop"

var _aggrCmdKindIndex = [...]uint8{0, 11, 22}

const _aggrCmdKindLowerName = "aggrcmddataaggrcmdstop"

func (i aggrCmdKind) String() string {
	if i >= aggrCmdKind(len(_aggrCmdKindIndex)-1) {
		return fmt.Sprintf("aggrCmdKind(%d)", i)
	}
	return _aggrCmdKindName[_aggrCmdKindIndex[i]:_aggrCmdKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _aggrCmdKindNoOp() {
	var x [1]struct{}
	_ = x[aggrCmdData-(0)]
	_ = x[aggrCmdStop-(1)]
}

var _aggrCmdKindValues = []aggrCmdKind{aggrCmdData, aggrCmdStop}

var _aggrCmdKindNameToValueMap = map[string]aggrCmdKind{
	_aggrCmdKindName[0:11]:       aggrCmdData,
	_aggrCmdKindLowerName[0:11]:  aggrCmdData,
	_aggrCmdKindName[11:22]:      aggrCmdStop,
	_aggrCmdKindLowerName[11:22]: aggrCmdStop,
}

var _aggrCmdKindNames = []string{
	_aggrCmdKindName[0:11],
	_aggrCmdKindName[11:22],
}

// aggrCmdKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func aggrCmdKindString(s string) (aggrCmdKind, error) {
	if val, ok := _aggrCmdKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _aggrCmdKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to aggrCmdKind values", s)
}

// aggrCmdKindValues returns all values of the enum
func aggrCmdKindValues() []aggrCmdKind {
	return _aggrCmdKindValues
}

// aggrCmdKindStrings returns a slice of all String values of the enum
func aggrCmdKindStrings() []string {
	strs := make([]string, len(_aggrCmdKindNames))
	copy(strs, _aggrCmdKindNames)
	return strs
}

// IsAaggrCmdKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i aggrCmdKind) IsAaggrCmdKind() bool {
	for _, v := range _aggrCmdKindValues {
		if i == v {
			return true
		}
	}
	return false
}
