// Code generated by "enumer -type DurationKind"; DO NOT EDIT.

package metrics

import (
	"fmt"
	"strings"
)

const _DurationKindName = "AddSubdurationKindSize"

var _DurationKindIndex = [...]uint8{0, 3, 6, 22}

const _DurationKindLowerName = "addsubdurationkindsize"

func (i DurationKind) String() string {
	if i >= DurationKind(len(_DurationKindIndex)-1) {
		return fmt.Sprintf("DurationKind(%d)", i)
	}
	return _DurationKindName[_DurationKindIndex[i]:_DurationKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DurationKindNoOp() {
	var x [1]struct{}
	_ = x[Add-(0)]
	_ = x[Sub-(1)]
	_ = x[durationKindSize-(2)]
}

var _DurationKindValues = []DurationKind{Add, Sub, durationKindSize}

var _DurationKindNameToValueMap = map[string]DurationKind{
	_DurationKindName[0:3]:       Add,
	_DurationKindLowerName[0:3]:  Add,
	_DurationKindName[3:6]:       Sub,
	_DurationKindLowerName[3:6]:  Sub,
	_DurationKindName[6:22]:      durationKindSize,
	_DurationKindLowerName[6:22]: durationKindSize,
}

var _DurationKindNames = []string{
	_DurationKindName[0:3],
	_DurationKindName[3:6],
	_DurationKindName[6:22],
}

// DurationKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DurationKindString(s string) (DurationKind, error) {
	if val, ok := _DurationKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DurationKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DurationKind values", s)
}

// DurationKindValues returns all values of the enum
func DurationKindValues() []DurationKind {
	return _DurationKindValues
}

// DurationKindStrings returns a slice of all String values of the enum
func DurationKindStrings() []string {
	strs := make([]string, len(_DurationKindNames))
	copy(strs, _DurationKindNames)
	return strs
}

// IsADurationKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DurationKind) IsADurationKind() bool {
	for _, v := range _DurationKindValues {
		if i == v {
			return true
		}
	}
	return false
}
