// Code generated by "enumer -type RequestKind"; DO NOT EDIT.

package metrics

import (
	"fmt"
	"strings"
)

const _RequestKindName = "OkOverloadBadRequestFailedrequestKindSize"

var _RequestKindIndex = [...]uint8{0, 2, 10, 20, 26, 41}

const _RequestKindLowerName = "okoverloadbadrequestfailedrequestkindsize"

func (i RequestKind) String() string {
	if i >= RequestKind(len(_RequestKindIndex)-1) {
		return fmt.Sprintf("RequestKind(%d)", i)
	}
	return _RequestKindName[_RequestKindIndex[i]:_RequestKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RequestKindNoOp() {
	var x [1]struct{}
	_ = x[Ok-(0)]
	_ = x[Overload-(1)]
	_ = x[BadRequest-(2)]
	_ = x[Failed-(3)]
	_ = x[requestKindSize-(4)]
}

var _RequestKindValues = []RequestKind{Ok, Overload, BadRequest, Failed, requestKindSize}

var _RequestKindNameToValueMap = map[string]RequestKind{
	_RequestKindName[0:2]:        Ok,
	_RequestKindLowerName[0:2]:   Ok,
	_RequestKindName[2:10]:       Overload,
	_RequestKindLowerName[2:10]:  Overload,
	_RequestKindName[10:20]:      BadRequest,
	_RequestKindLowerName[10:20]: BadRequest,
	_RequestKindName[20:26]:      Failed,
	_RequestKindLowerName[20:26]: Failed,
	_RequestKindName[26:41]:      requestKindSize,
	_RequestKindLowerName[26:41]: requestKindSize,
}

var _RequestKindNames = []string{
	_RequestKindName[0:2],
	_RequestKindName[2:10],
	_RequestKindName[10:20],
	_RequestKindName[20:26],
	_RequestKindName[26:41],
}

// RequestKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RequestKindString(s string) (RequestKind, error) {
	if val, ok := _RequestKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RequestKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RequestKind values", s)
}

// RequestKindValues returns all values of the enum
func RequestKindValues() []RequestKind {
	return _RequestKindValues
}

// RequestKindStrings returns a slice of all String values of the enum
func RequestKindStrings() []string {
	strs := make([]string, len(_RequestKindNames))
	copy(strs, _RequestKindNames)
	return strs
}

// IsARequestKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RequestKind) IsARequestKind() bool {
	for _, v := range _RequestKindValues {
		if i == v {
			return true
		}
	}
	return false
}
